import { ToolCategory } from './types';
import { FileText, Scissors, PenTool, Type, Search, Hash, AlignLeft, CaseUpper, RefreshCw, Link, Code2, Braces, Terminal, MessageSquare, Lock, Sparkles, ImageIcon, Scaling, Crop, Layers, Wand2, Pipette, GraduationCap, Calculator, BookOpen, Settings, QrCode, Bot, Cpu, BarChart, Tag, FileSearch, LayoutGrid, FileX, Code, ImagePlus, Globe, TrendingUp, LayoutTemplate, Palette, TestTube,GitMerge, Puzzle, Shield,Key, Timer, AlarmClock, Clipboard, Compass, Mic, Video, Volume2, Share2, Wifi, BatteryCharging, Bluetooth, Cloud, Upload, Download, Database, Server, HardDrive, MousePointer, Touchpad, Keyboard, Printer, Monitor, Speaker, Webcam, Disc, Save, Trash2, Edit, Award, Bookmark, Calendar, Clock, CreditCard, DollarSign, Gift, Heart, Home, Map, Package, ShoppingCart, Star, ThumbsUp, ToggleLeft, TrafficCone, Truck, User, Users, Wind, Zap } from 'lucide-react';

export const ALL_TOOLS_DATA: ToolCategory[] = [
    {
        id: 'pdf',
        title: 'PDF Tools',
        mainIcon: FileText,
        description: 'Merge & Edit',
        gradientFrom: 'from-blue-900/80',
        gradientTo: 'to-blue-950/90',
        borderColor: 'border-blue-500/30',
        shadowColor: 'shadow-blue-500/20',
        subTools: [
            { id: 'pdf-split', name: 'Split PDF', icon: Scissors },
            { id: 'pdf-sign', name: 'Sign PDF', icon: PenTool },
            { id: 'pdf-merge', name: 'Merge PDF', icon: GitMerge },
            { id: 'pdf-compress', name: 'Compress PDF', icon: Scaling },
            { id: 'pdf-unlock', name: 'Unlock PDF', icon: Lock },
            { id: 'pdf-protect', name: 'Protect PDF', icon: Shield },
            { id: 'pdf-rotate', name: 'Rotate PDF', icon: RefreshCw },
            { id: 'pdf-to-word', name: 'PDF to Word', icon: FileText },
            { id: 'pdf-to-excel', name: 'PDF to Excel', icon: FileText },
            { id: 'pdf-to-ppt', name: 'PDF to PowerPoint', icon: FileText },
            { id: 'word-to-pdf', name: 'Word to PDF', icon: FileText },
            { id: 'excel-to-pdf', name: 'Excel to PDF', icon: FileText },
            { id: 'ppt-to-pdf', name: 'PowerPoint to PDF', icon: FileText },
            { id: 'pdf-to-jpg', name: 'PDF to JPG', icon: ImageIcon },
            { id: 'jpg-to-pdf', name: 'JPG to PDF', icon: ImageIcon },
        ]
    },
    {
        id: 'text',
        title: 'Text Tools',
        mainIcon: Type,
        description: 'Format & Analyze',
        gradientFrom: 'from-zinc-800/90',
        gradientTo: 'to-zinc-900/90',
        borderColor: 'border-zinc-500/30',
        shadowColor: 'shadow-zinc-500/20',
        subTools: [
            { id: 'text-extractor', name: 'Text Extractor', icon: Search },
            { id: 'text-counter', name: 'Word Counter', icon: Hash },
            { id: 'text-diff', name: 'Diff Checker', icon: AlignLeft },
            { id: 'text-case-converter', name: 'Case Converter', icon: CaseUpper },
            { id: 'text-reverse', name: 'Reverse Text', icon: RefreshCw },
            { id: 'text-slugify', name: 'Slugify Text', icon: Link },
            { id: 'text-generator', name: 'Lorem Ipsum Generator', icon: FileText },
            { id: 'text-summarizer', name: 'Text Summarizer', icon: Sparkles },
            { id: 'text-to-speech', name: 'Text to Speech', icon: Volume2 },
            { id: 'speech-to-text', name: 'Speech to Text', icon: Mic },
        ]
    },
    {
        id: 'dev',
        title: 'Developer Tools',
        mainIcon: Code2,
        description: 'Code & API',
        gradientFrom: 'from-gray-900/90',
        gradientTo: 'to-black/90',
        borderColor: 'border-emerald-500/20',
        shadowColor: 'shadow-emerald-500/10',
        subTools: [
            { id: 'dev-json-formatter', name: 'JSON Formatter', icon: Braces },
            { id: 'dev-api-tester', name: 'API Tester', icon: Terminal },
            { id: 'dev-ask-ai', name: 'AI Code Generator', icon: MessageSquare },
            { id: 'dev-url-encoder', name: 'URL Encoder', icon: Link },
            { id: 'dev-url-decoder', name: 'URL Decoder', icon: Link },
            { id: 'dev-base64-encoder', name: 'Base64 Encoder', icon: Code2 },
            { id: 'dev-base64-decoder', name: 'Base64 Decoder', icon: Code2 },
            { id: 'dev-jwt-decoder', name: 'JWT Decoder', icon: Lock },
            { id: 'dev-code-beautifier', name: 'Code Beautifier', icon: Sparkles },
            { id: 'dev-regex-tester', name: 'Regex Tester', icon: TestTube },
            { id: 'dev-port-scanner', name: 'Port Scanner', icon: Search },
            { id: 'dev-dns-lookup', name: 'DNS Lookup', icon: Globe },
            { id: 'dev-ip-lookup', name: 'IP Lookup', icon: Map },
        ]
    },
    {
        id: 'image',
        title: 'Image Tools',
        mainIcon: ImageIcon,
        description: 'Edit & Resize',
        gradientFrom: 'from-indigo-900/80',
        gradientTo: 'to-purple-950/90',
        borderColor: 'border-purple-500/30',
        shadowColor: 'shadow-purple-500/20',
        subTools: [
            { id: 'img-resizer', name: 'Image Resizer', icon: Scaling },
            { id: 'img-cropper', name: 'Image Cropper', icon: Crop },
            { id: 'img-converter', name: 'Image Converter', icon: Layers },
            { id: 'img-filters', name: 'Image Filters', icon: Wand2 },
            { id: 'img-color-picker', name: 'Color Picker', icon: Pipette },
            { id: 'img-compressor', name: 'Image Compressor', icon: Scaling },
            { id: 'img-to-text', name: 'Image to Text (OCR)', icon: Type },
            { id: 'img-bg-remover', name: 'Background Remover', icon: Scissors },
            { id: 'img-watermark', name: 'Add Watermark', icon: PenTool },
        ]
    },
    {
        id: 'seo',
        title: 'SEO Tools',
        mainIcon: BarChart,
        description: 'Web Rank',
        gradientFrom: 'from-cyan-900/80',
        gradientTo: 'to-sky-950/90',
        borderColor: 'border-cyan-500/30',
        shadowColor: 'shadow-cyan-500/20',
        subTools: [
            { id: 'seo-keyword-research', name: 'Keyword Research', icon: Tag },
            { id: 'seo-meta-tag-generator', name: 'Meta Tag Generator', icon: Code2 },
            { id: 'seo-content-optimizer', name: 'Content Optimizer', icon: FileSearch },
            { id: 'seo-headline-analyzer', name: 'Headline Analyzer', icon: Type },
            { id: 'seo-report-generator', name: 'SEO Report Generator', icon: TrendingUp },
            { id: 'seo-sitemap-generator', name: 'Sitemap Generator', icon: LayoutGrid },
            { id: 'seo-robots-txt-generator', name: 'Robots.txt Generator', icon: FileX },
            { id: 'seo-schema-markup-generator', name: 'Schema Markup Generator', icon: Code },
            { id: 'seo-image-alt-text-generator', name: 'Image Alt Text Generator', icon: ImagePlus },
            { id: 'seo-serp-simulator', name: 'SERP Simulator', icon: Monitor },
            { id: 'seo-backlink-checker', name: 'Backlink Checker', icon: Link },
            { id: 'seo-website-analyzer', name: 'Website Analyzer', icon: Search },
        ]
    },
    {
        id: 'converter',
        title: 'Converter Tools',
        mainIcon: RefreshCw,
        description: 'Convert Anything',
        gradientFrom: 'from-green-900/80',
        gradientTo: 'to-emerald-950/90',
        borderColor: 'border-green-500/30',
        shadowColor: 'shadow-green-500/20',
        subTools: [
            { id: 'converter-length', name: 'Length Converter', icon: Scaling },
            { id: 'converter-weight', name: 'Weight Converter', icon: Scaling },
            { id: 'converter-temperature', name: 'Temperature Converter', icon: Thermometer },
            { id: 'converter-currency', name: 'Currency Converter', icon: DollarSign },
            { id: 'converter-time', name: 'Time Converter', icon: Clock },
            { id: 'converter-data', name: 'Data Converter', icon: Database },
            { id: 'converter-speed', name: 'Speed Converter', icon: Wind },
        ]
    },
    {
        id: 'utility',
        title: 'Utility Tools',
        mainIcon: Settings,
        description: 'Daily Helpers',
        gradientFrom: 'from-emerald-900/80',
        gradientTo: 'to-teal-950/90',
        borderColor: 'border-teal-500/30',
        shadowColor: 'shadow-teal-500/20',
        subTools: [
            { id: 'util-unit-converter', name: 'Unit Converter', icon: RefreshCw },
            { id: 'util-password-generator', name: 'Password Generator', icon: Lock },
            { id: 'util-qr-code-generator', name: 'QR Code Generator', icon: QrCode },
            { id: 'util-random-number-generator', name: 'Random Number Generator', icon: Hash },
            { id: 'util-stopwatch', name: 'Stopwatch', icon: Timer },
            { id: 'util-countdown-timer', name: 'Countdown Timer', icon: AlarmClock },
            { id: 'util-notes', name: 'Notes', icon: Clipboard },
        ]
    },
];
